### ISSUE TITLE
Is the "Dependencies" section relevant?

### ISSUE THREAD

**Issue by yoavweiss** [w3c/performance-timeline#106]
It seems like the [Dependencies](https://w3c.github.io/performance-timeline/#dependencies) section is out of date, and I'm not sure it's necessary.
I couldn't find any dependency on PerformanceResourceTiming and initiatorType even though they are listed there. I'm guessing we had such a dependency, but it's no longer there.

Otherwise, can't we simply make sure that any dependency is properly linked, and delete this entire section?

@igrigorik - WDYT?

**Comment by igrigorik** [comment]
Thanks Marcos.

Doing a quick spot check through current dfn's: most of the concepts we only use once, and some not at all. Given that, I think I'd be OK removing that section.
