### ISSUE TITLE
Broken link to non-existent anchor in WebIDL spec

### ISSUE THREAD

**Issue by mstange** [w3c/performance-timeline#110]
In the [conformance section](https://w3c.github.io/performance-timeline/#conformance), the words "conforming IDL fragments" link to a non-existent anchor. The suggested sentence from the current version of the WebIDL spec is the following, where "conforming sets of IDL fragments" should link to https://heycam.github.io/webidl/#dfn-conforming-set-of-idl-fragments: "The IDL fragment in Appendix A of this specification must, in conjunction with the IDL fragments defined in this specification’s normative references, be interpreted as required for conforming sets of IDL fragments, as described in the “Web IDL” specification. [WEBIDL]"

**Comment by npm1** [comment]
Is this issue obsolete? I do not find "conforming IDL fragments" in the spec.

**Comment by npm1** [comment]
Ok closing now, but feel free to comment if you still see the broken link
