### ISSUE TITLE
supported entry types needs to be context aware

### ISSUE THREAD

**Issue by cvazac** [w3c/performance-timeline#113]
Currently, [`supported entry types`](https://github.com/w3c/performance-timeline/blob/gh-pages/index.html#L564) is specific to the user agent. It also needs to be _context_ (window v. worker) aware, because `navigation` entries are **not** observable from workers, for example.

**Comment by toddreifsteck** [comment]
Triaged this for possible fix in L2. Multiple other specifications most likely need their registrations to be context aware and ideally should build on language in this spec. They can monkey patch if needed but it is not ideal.

**Comment by npm1** [comment]
@cvazac assigning to you per the discussion during the call
