### ISSUE TITLE
Relevant global object for 'relevant performance entry buffer'

### ISSUE THREAD

**Issue by npm1** [w3c/performance-timeline#122]
Currently this is defined as 'The relevant performance entry buffer is the performance entry buffer associated with the relevant global object.' This is ambiguous.

@yoavweiss

**Comment by yoavweiss** [comment]
I believe this is addressed in the https://github.com/w3c/performance-timeline/pull/123/files#diff-eacf331f0ffc35d4b482f1d15a887d3bR222

**Comment by yoavweiss** [comment]
At the same time, we probably want to backport that definition for L2.

**Comment by yoavweiss** [comment]
Closed by #129
