### ISSUE TITLE
Republish L2 based on the latest "level2" branch

### ISSUE THREAD

**Issue by yoavweiss** [w3c/performance-timeline#124]
It seems like the current [L2 spec](https://www.w3.org/TR/performance-timeline-2/) is not based on the latest in its branch, where we removed the "buffered" flag, so we need to republish it.

@plehegar or @siusin - can you assist?

**Comment by yoavweiss** [comment]
Haven't discussed on the call yesterday, but note that there's [issue #117](https://github.com/w3c/performance-timeline/issues/117) around the definition of supportedEntryTypes that's an L2 blocker

**Comment by siusin** [comment]
hi @yoavweiss 
I'm not sure which is the current latest branch... do you mean we need to republish the spec in [/TR ](https://www.w3.org/TR/performance-timeline-2/) based on the [level2](https://github.com/w3c/performance-timeline/tree/level2) branch? or simply the current gh-pages branch?

**Comment by yoavweiss** [comment]
Yeah, I meant to republish based on the [level2](https://github.com/w3c/performance-timeline/tree/level2) branch, where we had the buffered flag removed.
