### ISSUE TITLE
How does "queue a PerformanceEntry" algorithm interact with other specs?

### ISSUE THREAD

**Issue by jdm** [w3c/performance-timeline#128]
This spec does not contain any algorithms which interact with https://w3c.github.io/performance-timeline/#queue-a-performanceentry. I haven't found any in Fetch or HTML either. What is the integration model? I'm trying to find cases where the optional "add to performance entry buffer" flag would be set, and it seems very complex so far.

**Comment by jdm** [comment]
I have found step 21 of https://w3c.github.io/resource-timing/#sec-process, which does not set the flag, followed by step 22 which append the entry to the performance entry buffer. It's very confusing why these are differentiated.

**Comment by jdm** [comment]
Step 10 and 11 of https://w3c.github.io/user-timing/#dom-performance-measure have the same differentiation.

**Comment by npm1** [comment]
There is no longer an optional flag in the queue an entry algorithm. Is this issue still relevant or can it be closed?

**Comment by jdm** [comment]
Nope, that's a useful improvement!

**Comment by npm1** [comment]
Actually this looks like recently removed in a commit which needs to be reverted, let me reopen this and we can look when the repo is in a reasonable state.

**Comment by npm1** [comment]
Ok, now that the spec is fixed it still looks like the flag in the algorithm does not exist, so closing this. Feel free to comment/reopen/file another issue as needed.
