### ISSUE TITLE
"relevant performance entry tuple" usage is still broken

### ISSUE THREAD

**Issue by bzbarsky** [w3c/performance-timeline#130]
Unfortunately, my feedback on https://github.com/w3c/performance-timeline/pull/96 wasn't addressed properly, and I finally got far enough in my backlog to check it over...

In particular, https://w3c.github.io/performance-timeline/#dfn-relevant-performance-entry-tuple is used from two places: https://w3c.github.io/performance-timeline/#observe-method and <https://w3c.github.io/performance-timeline/#queue-a-performanceentry>.  It then proceeds to examine "relevant global object of the context object".

This is maybe OK in the `observe()` case, though ideally the reference to "context object" would be in the `observe()` steps, where it's clear what that is, and "relevant performance entry tuple" would be handed that object as an argument.

But in the "queue a PerformanceEntry" case, there isn't a context object at all.  It's an abstract spec algorithm, without a "this" (which is what "context object" represents).  It does have a `PerformanceEntry` argument, but if the global of _that_ is meant, that needs to be stated explicitly.  Again, having an argument for the object to use would help here.

**Comment by bzbarsky** [comment]
@spanicker @igrigorik @npm1

**Comment by npm1** [comment]
Yep, I can fix that. Thanks for filing the issue!

**Comment by bzbarsky** [comment]
That looks much better, thank you!
