### ISSUE TITLE
Spec errors related to DOMHighResTimestamp

### ISSUE THREAD

**Issue by yoavweiss** [w3c/performance-timeline#136]
I'm seeing the following error:
"Couldn't match "DOMHighResTimeStamp" to anything in the document or to any other spec. Please provide a data-cite attribute for it. at: 1, 2, 3, 4."

At the same time, the spec is not reffing DOMHighResTimestamp anywhere other than the IDL. Did something around that break?

/cc @marcoscaceres @plehegar

**Comment by plehegar** [comment]
Shepherd seems to have lost of webperf references. https://respec.org/xref/ returns empty with "DOMHighResTimestamp".

**Comment by yoavweiss** [comment]
Seems like this was fixed by whatever fixes Shepherd. Closing.

**Comment by marcoscaceres** [comment]
@plehegar see my email. We need to republish the specs on TR with the proper annotations that ReSpec is now producing. Then we will be in cross-reference nirvana 😁. Be nice to also get these specs on auto-publish if they are stable enough.
