### ISSUE TITLE
Timing of the observer callbacks is not defined

### ISSUE THREAD

**Issue by esprehn** [w3c/performance-timeline#14]
The spec needs to specify a task source, and how the callbacks are queued, and when they're called. It also needs to specify what the callback this value is.

Please see MutationObservers for how to correctly spec this:
https://dom.spec.whatwg.org/#mutation-observers
https://heycam.github.io/webidl/#dfn-callback-this-value

The spec needs detailed steps for what to do in each step and how to execute each algorithm.

**Comment by esprehn** [comment]
Note that specifically it seems like from one of the examples that you might get synchronously notified of existing records which seems bad. The spec should talk about how and when to queue tasks for notify you.

**Comment by igrigorik** [comment]
Merging into #12, let's continue this there.
