### ISSUE TITLE
`buffered: true` not adding entries to PerformanceObserver's buffer

### ISSUE THREAD

**Issue by hsm2** [w3c/performance-timeline#145]
Hey, so I'm working on adding a PerformanceObserver to my project.
```
if ('PerformanceObserver' in window) {
  const performanceObserver = new PerformanceObserver((list) => {
  list
    .getEntries()
    .forEach((entry) => {
      console.log(entry);
    });
  });
  performanceObserver.observe({ entryTypes: ['resource'], buffered: true });
}
```
I find that PerformanceEntries from before the `observe()` call do not call the `callbackFunc`.

If I add
`window.performance.getEntriesByType('resource').forEach((entry) => console.log(entry));` before the `if` block, entries are logged that weren't logged by the `callbackFunc`

I thought that the performance entries are added to the observer's buffer if `buffered: true`, can someone tell me what could be going on? Thanks!

**Comment by tdresser** [comment]
Sounds like this could be a Chrome bug.

npm1@, can you verify, and if it is, move this over to Chrome's bug tracker?

**Comment by npm1** [comment]
Hi @hsm2 your understanding is correct but this is a new addition to the spec and browsers are just starting to implement this. In particular in Chrome this will be available in Chrome 77 release. Feel free to try it out in Chrome Canary and file a bug in http://crbug.com/new if this is not working as you expect it. Closing this.
