### ISSUE TITLE
DOMHighResTimeStamp not found in level2

### ISSUE THREAD

**Issue by npm1** [w3c/performance-timeline#153]
I recently submitted a fix to move the constructor in Level2 because ReSpec would highlight the WebIDL section in red otherwise. But now after that fix I still get a problem about DOMHighResTimeStamp not being found in the PerformanceEntry WebIDL entry. I don't see this problem in gh-pages branch but it is present in level2 branch. @marcoscaceres do you have any idea how I can fix this?

**Comment by npm1** [comment]
And now... if we could republish the level2 branch onto https://www.w3.org/TR/performance-timeline-2/ that would be great @plehegar since currently it has a bunch of red highlighting due to ReSpec

**Comment by plehegar** [comment]
done
