### ISSUE TITLE
Spec needs to clarify what to do with existing records when observing

### ISSUE THREAD

**Issue by esprehn** [w3c/performance-timeline#16]
When you call ```observe()``` do you get notified of records that match that are in the buffer at that time?

**Comment by igrigorik** [comment]
Which buffer? Different event types have different buffers.. I'm inclined to say that you shouldn't, you should only observe events post-subscription.

**Comment by esprehn** [comment]
That seems reasonable to me, the spec should day that.

**Comment by mpb** [comment]
Spec already seems to say that.
observer.observe() says "This method instructs the user agent to register the observer and report any new performance entries based on the criteria given by options."

And the main observer description says "The PerformanceObserver interface can be used to observe the Performance Timeline and be notified of new performance entries as they are recorded by the user agent."

I can add a note to the 'observe' method saying NOTE: this callback will be invoked with new performance entries generated AFTER the observer is created. There is no expectation that the PerformanceObserverCallback will be notified of any existing entries in the global performance timeline buffer(s).

SG?

**Comment by igrigorik** [comment]
FWIW, I think the current language is sufficient. The suggested note makes it sound ('no expectation') that some UA's might be allowed to do otherwise.

**Comment by mpb** [comment]
@esprehn?

**Comment by igrigorik** [comment]
Talked on the call, will resolve as part of #12.
