### ISSUE TITLE
Use of "SyntaxError" seems incorrect, should be TypeError

### ISSUE THREAD

**Issue by noamr** [w3c/performance-timeline#163]
In 3.3.1, it is specified that when entryTypes/type is omitted, a SyntaxError should be thrown.
However, SyntaxError are reserved for parsers (like JS syntax, CSS syntax) - not to semantic exceptions such as this one, which should probably be a TypeError.

**Comment by npm1** [comment]
This was added in https://github.com/w3c/performance-timeline/pull/112. @yoavweiss do you recall if we considered TypeError here or not? I think I'd be ok changing it to TypeError.

**Comment by yoavweiss** [comment]
Past me [thought SyntaxError seems like the best fit](https://github.com/w3c/performance-timeline/pull/112#discussion_r241829920).

I believe we were aiming for a "SyntaxError" [DOMException](https://heycam.github.io/webidl/#idl-DOMException-error-names) and not a simple exception, so IIUC it doesn't necessarily refer to parsers. 
I agree it's not ideal, but so does TypeError. A BadInput exception would've been ideal.

**Comment by noamr** [comment]
OK; Maybe then separate PerformanceObserverInit to PerformanceObsrverInitSingle with type+bufferred and PerformanceObserverInitMultiple with entryTypes? That way the IDL-generated code can emit this syntax error automatically... If there is some concensus on this I can suggest a PR

**Comment by yoavweiss** [comment]
That seems like a not-web-exposed change, and could potentially simplify the processing, and enable us to deprecate the "multiple" type in the future.

@npm1 - thoughts?

**Comment by npm1** [comment]
Can you clarify precisely what the proposed IDL change is here? I'm not sure I follow.

**Comment by noamr** [comment]
> Can you clarify precisely what the proposed IDL change is here? I'm not sure I follow.
Sure! something like:
`
dictionary PerformanceObserverInitMultple {
  sequence<DOMString> entryTypes;
};
dictionary PerformanceObserverInitSingle {
  sequence<DOMString> entryTypes;
  DOMString type;
  boolean buffered;
};
...
void observe (optional (PerformanceObserverInitSingle or PerformanceObserverInitMultiple) options = {});
`

**Comment by npm1** [comment]
Oh I see. Assuming we're sure that it's valid IDL, I'm ok with that.

**Comment by npm1** [comment]
I started writing a PR for this but then I realized that the suggestion is not possible. Per https://heycam.github.io/webidl/#ref-for-dfn-distinguishable%E2%91%A2 you can only use distinguishable types in an 'or', and dictionaries are not distinguishable from each other.

So I'll just send a PR to change the error to TypeError.
