### ISSUE TITLE
Lazy prefix on LazyPerformanceEntryList doesn't add value

### ISSUE THREAD

**Issue by esprehn** [w3c/performance-timeline#17]
This should be called a PerformanceEntrySublist or something, there doesn't seem to be any value in the "Lazy" prefix. Indeed the word lazy isn't even mentioned in the spec outside the interface name.

**Comment by mpb** [comment]
How about PerformanceObserverEntries to be consistent with the other typenames?

**Comment by igrigorik** [comment]
http://w3c.github.io/performance-timeline/#idl-def-PerformanceEntryList

If we're shooting for consistency: PerformanceObserverEntryList? Long, but consistent :)

**Comment by mpb** [comment]
Sounds good to me. Updated #22.
