### ISSUE TITLE
Auto-publishing failures

### ISSUE THREAD

**Issue by yoavweiss** [w3c/performance-timeline#201]
@caribouW3 - auto-publishing seems to fail with [this error](https://labs.w3.org/echidna/api/status?id=b2c494d0-a570-4bc0-9c14-744ec59d507c) which seems familiar. Can you take a look?

**Comment by caribouW3** [comment]
It's similar to the User Timing case, it's in CR now, do we need a CR draft or a CR snapshot?

**Comment by yoavweiss** [comment]
A CR draft seems sufficient

**Comment by clelland** [comment]
@caribouW3, was anything done to address this?

The document in TR is still a CR snapshot from December 2021 -- although there haven't been any new commits to this repo since July that might have triggered publishing.

**Comment by caribouW3** [comment]
It should be fixed in https://github.com/w3c/performance-timeline/pull/203

**Comment by caribouW3** [comment]
Closing, PR 203 and 204 merged.
