### ISSUE TITLE
Gsoc 2023 Proposal clock-drift correction

### ISSUE THREAD

**Issue by Forchapeatl** [w3c/performance-timeline#208]
![image](https://user-images.githubusercontent.com/24577149/223628299-274aa64d-ec0d-4c24-93b4-9648aa71f650.png)

Please , correct me if I am wrong / mislead 

when it comes to measuring  the time taken for a task to accomplish results we can use  the system clock `Date.now()`
```js
var mark_start = Date.now();
doTask(); // Some task
var duration = Date.now() - mark_start;
```

But the difference between start-end using Date.now() can't be trusted as a change in the user's system time would skew the results.
```js
var mark_start = performance.now();
doTask(); // Some task
var duration = performance.now() - mark_start;

```

Similarly we can use the monotonic clock `Performance.now()` - which relative to page load . But a difference between start-end of performance.now() can't be used as the underlying clock potentially stops if the user sleeps their device.

Hence we need to account for time which is   reliable across sleep / wake cycles during task execution.
```js
clockOffset = new Date() - performance.timeOrigin - performance.now()
```

Options (1)  is fine if you ask me.  Since we are accounting for two different clocks option (2) might cost confusion as the drift behavior is different on platforms.  Option (3) seems to require the some replication of entry attributes and seems more complex than it sounds. 

Just to clarify , option (1) means the  PerformanceEntry will have 5 attributes: `name`, `entryType`,` startTime`, `duration` and `clockOffset` ?

_Originally posted by @Forchapeatl in https://github.com/w3c/performance-timeline/issues/206#issuecomment-1459614219_

**Comment by Forchapeatl** [comment]
Hello @noamr , as a result of this [comment](https://github.com/w3c/performance-timeline/issues/206#issuecomment-1462524855) . Please , I don't really know how to approach you in regards to gsoc. I thought it will be better to respectfully create a new issue to address my worries. Please , is this okay with you ?

**Comment by noamr** [comment]
> Hello @noamr , as a result of this [comment](https://github.com/w3c/performance-timeline/issues/206#issuecomment-1462524855) . Please , I don't really know how to approach you in regards to gsoc. I thought it will be better to respectfully create a new issue to address my worries. Please , is this okay with you ?

Please go through the standard GSOC process and don't post here as requested.
