### ISSUE TITLE
"Queue a navigation performance entry" doesn't seem to be used

### ISSUE THREAD

**Issue by yoavweiss** [w3c/performance-timeline#209]
Navigation Timing defines [its own algorithm](https://www.w3.org/TR/navigation-timing-2/#dfn-queue-the-navigation-timing-entry) for that. (which also doesn't seem to be called from anywhere)

^^ @noamr

**Comment by noamr** [comment]
It's called from the HTML spec, here: https://html.spec.whatwg.org/#the-end:queue-the-navigation-timing-entry

**Comment by clelland** [comment]
That algorithm in Navigation Timing should be calling "Queue a navigation performance entry" rather than "queue a performance entry" in the link from "queue".
