### ISSUE TITLE
startTime is relative to time origin of PerformanceEntry object's global

### ISSUE THREAD

**Issue by plehegar** [w3c/performance-timeline#25]
You'd probably want to make it explicitly clear that 
 http://w3c.github.io/performance-timeline/#widl-PerformanceEntry-startTime 
 is relative to the time origin of the PerformanceEntry object's global, 
 as defined in hr-time.

**Comment by plehegar** [comment]
Since we fixed hr-time to better define the time origin, I believe this issue can be closed with no action.

**Comment by igrigorik** [comment]
Figures.. My bad, apologies!

**Comment by igrigorik** [comment]
Yep, closing.
