### ISSUE TITLE
PerformanceEntry.startTime/duration should be DOMHighResTimeStamp

### ISSUE THREAD

**Issue by foolip** [w3c/performance-timeline#31]
http://w3c.github.io/performance-timeline/#the-performanceentry-interface

`DOMString` looks like a typo in the IDL, since the definitions talk about `DOMHighResTimeStamp`.

**Comment by igrigorik** [comment]
@plehegar sanity check: typo, or was this intentional?

**Comment by toddreifsteck** [comment]
This appears to be a typo from my review. Curious what @plehegar says

**Comment by eliperelman** [comment]
I think typo, [1] and others specifically say `DOMHighResTimeStamp`:

[1] http://www.w3.org/TR/user-timing/#performancemeasure

**Comment by plehegar** [comment]
Here is when the mistake was introduced. https://github.com/w3c/performance-timeline/commit/3c13485b34b16a0f53ddba344fa73910e99c89bb

Will produce a PR shortly.
