### ISSUE TITLE
Performance should be a partial interface?

### ISSUE THREAD

**Issue by foolip** [w3c/performance-timeline#32]
https://w3c.github.io/performance-timeline/#the-performance-interface

It was a partial interface in http://www.w3.org/TR/performance-timeline/#sec-window.performance-attribute and Performance is already defined by https://w3c.github.io/web-performance/specs/NavigationTiming/Overview.html#sec-window.performance-attribute

**Comment by igrigorik** [comment]
I believe this will be handled via https://github.com/w3c/performance-timeline/pull/26/files. 

For background, see: https://github.com/w3c/hr-time/pull/7

**Comment by foolip** [comment]
Is there also a spec to replace https://w3c.github.io/web-performance/specs/NavigationTiming/Overview.html#sec-window.performance-attribute with a partial interface? https://w3c.github.io/navigation-timing/ seems to be a delta spec. Should I file an issue for that?

**Comment by igrigorik** [comment]
@foolip apologies about the confusion.. We split the https://github.com/w3c/web-performance/tree/gh-pages/specs directory into separate repos, so all of those in w3c/web-performance is outdated. We should remove those.

/cc @plehegar

**Comment by foolip** [comment]
The problem is that https://w3c.github.io/navigation-timing/ looks like a delta spec, it doesn't include the interfaces that are defined in http://www.w3.org/TR/navigation-timing/

Is that not intentional?

In any case, I understand that https://w3c.github.io/hr-time/#the-performance-interface is now intended to be the main definition of the `Performance` interface, so thanks for clarifying!

**Comment by igrigorik** [comment]
> Is that not intentional?

Yes. Here's a quick top-down view: https://docs.google.com/document/d/1ZKW9N0cteHgK91SyYQONFuy2ZW6J4Oak398niTo232E/edit

**Comment by foolip** [comment]
In that document I don't see "Defines *PerformanceTiming* & *PerformanceNavigation* interfaces" next to any of the boxes, which is the discrepancy between http://www.w3.org/TR/navigation-timing/ and https://w3c.github.io/navigation-timing/

**Comment by foolip** [comment]
It does say "Extends *Performance* interface" for https://w3c.github.io/navigation-timing/ but that's currently not true. Me confused :)

**Comment by igrigorik** [comment]
Ah, good catch. We've refactored some of the interfaces..

* PerformanceTiming -> PerformanceNavigationTiming
* PerformanceNavigation -> part of PerformanceNavigationTiming

Updated the diagram.

**Comment by foolip** [comment]
Oh, I see, so is the hope that `Performance.timing` and `Performance.navigation` can be simply be removed? In some ad-hoc testing, those are already supported in Blink, Gecko, IE and WebKit...

Also, is there a way to actually get a `PerformanceNavigationTiming` object? https://w3c.github.io/navigation-timing/#sec-PerformanceNavigationTiming appears to only define the interface.

**Comment by igrigorik** [comment]
> Oh, I see, so is the hope that Performance.timing and Performance.navigation can be simply be removed? In some ad-hoc testing, those are already supported in Blink, Gecko, IE and WebKit...

I believe that was the intent. @plehegar can you confirm?

> Also, is there a way to actually get a PerformanceNavigationTiming object? https://w3c.github.io/navigation-timing/#sec-PerformanceNavigationTiming appears to only define the interface.

`performance.getEntriesByType("navigation")`

**Comment by foolip** [comment]
If that is the intention, four browser engines would have to change. Is there a super-compelling reason if so?

**Comment by foolip** [comment]
Continuing this discussion in https://github.com/w3c/navigation-timing/issues/22 since it's not this spec's issue, and this issue is closed too.
