### ISSUE TITLE
getEntries* are depending on the scope

### ISSUE THREAD

**Issue by plehegar** [w3c/performance-timeline#39]
PerformanceEntry objects are dependant on their scope, such as
 myWorker.getEntriesByType("navigation") --> empty list.

So, a bit of improvement for sentences like:
[[
For each available PerformanceEntry object (entryObject),
]]

**Comment by igrigorik** [comment]
Perhaps something like...

> For each PerformanceEntry object (entryObject) associated with the [context object](http://www.w3.org/TR/dom/#context-object), in chronological order with...

/cc @bzbarsky for a sanity check :)

**Comment by bzbarsky** [comment]
Seems ok at first glance, assuming that PerformanceEntry objects have an explicit concept of being associated with something.

**Comment by igrigorik** [comment]
Yep, I think that'll get resolved in a separate thread where we more formally define the performance timeline processing model (https://github.com/w3c/performance-timeline/pull/12, https://github.com/w3c/performance-timeline/issues/13).
