### ISSUE TITLE
Add firstPaint PerformanceEntry

### ISSUE THREAD

**Issue by zbraniecki** [w3c/performance-timeline#4]
Out of the list of proposed PerformanceEntries the one missing from my POV is the firstPaint. Each browser has a custom way of reporting it, and it would fit nicely to get this as part of the performance API instead.

See: http://dxr.mozilla.org/mozilla-central/source/toolkit/components/startup/StartupTimeline.h#15

Some use cases:
 - measuring time to first paint
 - allow developers to track cases where the paint happened before DOMContentLoadEnd or LoadEnd (which means potential flicker).

**Comment by igrigorik** [comment]
FWIW, I think we can use [Frame Timing](http://w3c.github.io/frame-timing/) to approximate this: listen for the first `render` event and use that as a proxy for first paint... or, listen for render/composite/other events over a period time to build a better approximation.

Closing this thread, if need be, let's pick it up on FT. 

/cc @mpb

**Comment by NE-SmallTown** [comment]
> listen for the first render event and use that as a proxy for first paint... or, listen for render/composite/other events over a period time to build a better approximation.

Hi, Could you give more details on this?

**Comment by igrigorik** [comment]
@NE-SmallTown see https://w3c.github.io/paint-timing/#example
