### ISSUE TITLE
Performance should implement EventTarget

### ISSUE THREAD

**Issue by nicjansma** [w3c/performance-timeline#42]
Before the definition of `performance` was [moved](https://github.com/w3c/navigation-timing/commit/c3d97c8c7957008d153fec5145a9c1400f2094e7#diff-eacf331f0ffc35d4b482f1d15a887d3b) from NavigationTiming2, it had an update to have `Performance` be an `EventTarget`:

`interface Performance : EventTarget`

I think this got lost when moved to the PerformanceTimeline?  For example, ResourceTiming's `onresourcetimingbufferfull` would still need it.

**Comment by plehegar** [comment]
It can moved again since we have only  partial interface definition in performance timeline now.

The base interface is defined in hr-time-2:
[[
[Exposed=(Window,Worker)]
interface Performance : EventTarget {
[...]
]]
http://www.w3.org/TR/hr-time-2/#idl-def-Performance

**Comment by nicjansma** [comment]
Yep thanks!
