### ISSUE TITLE
Clarify PerformanceObserver registration language in the spec

### ISSUE THREAD

**Issue by igrigorik** [w3c/performance-timeline#44]
Continuation of #43. In particular, this language:

> Otherwise, register the <a>performance observer</a> as an <dfn>observer</dfn> with the `options` as _options_ on the <a>Performance Timeline</a> visible from the <a>performance observer</a>'s context.

Related: https://github.com/w3c/performance-timeline/issues/40#issuecomment-122968408, https://github.com/w3c/performance-timeline/pull/43#issuecomment-125546138, and https://www.w3.org/Bugs/Public/show_bug.cgi?id=24652. 

@annevk @bzbarsky would appreciate any tips on how to spec this.. unclear on the plumbing.

**Comment by bzbarsky** [comment]
So we're doing `new PerformanceObserver` right?  What you presumably want is to get the global associated with that constructor (the global of the `Realm` of the function is what I think you want here) and then go from that global to the preformance timeline; how that last part works would be defined by whatever spec defines the performance timeline.

The Web IDL spec does talk about "the ECMAScript global environment associated with the interface object" so you could use that language too; we'd then define it carefully in the IDL spec.

**Comment by igrigorik** [comment]
@bzbarsky @mpb took a slightly different route (modeled on Mutation Observer) in #47. PTAL.

**Comment by annevk** [comment]
Why is that a good model here? Mutation observers have to deal with nodes moving between globals, is that relevant for performance timelines?

**Comment by igrigorik** [comment]
@annevk err, sorry that was poor wording on my part. By "modeled" I simply meant that it uses similar approach to keep track of registered observers.. ptal at the language in #47.

**Comment by annevk** [comment]
Right, I did. I'm wondering why you went with "unit of related similar-origin browsing contexts" rather than scoping it to a global as @bzbarsky suggested.

**Comment by igrigorik** [comment]
Perhaps not the best one: perf observer processing was already using that language. 

> Each [ECMAScript global environment][] has a <dfn>performance observer task queued flag</dfn> and an associated list of <a>registered performance observer</a> objects which is initially empty.
> ...
> Let <i>notify list</i> be a copy of [ECMAScript global environment][]'s list of <a>registered performance observer</a> objects.
> ...
> If the list of <a>registered performance observer</a> objects of the [the ECMAScript global environment associated with the interface object][] contains a <a>registered performance observer</a>...

Does that sound about right?

**Comment by annevk** [comment]
Yeah, modulo that HTML calls it "JavaScript global environment" or "environment settings object". Ugh, we should really figure out some consistent wording. @bzbarsky should probably sign off though, he knows this better.

**Comment by bzbarsky** [comment]
Yes, we need to figure out consistent wording.  We have "JavaScript global environment" (HTML), "Realm" (ES6), "ECMAScript global environment" (WebIDL).  These may or may not all be the same thing, but I think in practice they are.  Also, "environment settings object" is claimed by hixie to be subtly different from just "a global", but I have never quite understood what the difference is, and it's not spelled out anywhere.

Which is to say, that I have no clue what to call this thing, or even what "this thing" is, offhand.  :(

**Comment by annevk** [comment]
The difference between "environment settings object" and "global" is I think that the former is language-neutral. I'm not sure how strongly we need to care about that though.

**Comment by bzbarsky** [comment]
I seem to recall hixie claiming that the relationship between environment settings objects and globals was not 1-1...

**Comment by igrigorik** [comment]
Hmm, so what's the verdict here? Should I go with the WebIDL version? :)

**Comment by igrigorik** [comment]
@annevk should I block this on https://github.com/whatwg/html/issues/167? Can't tell which way you're intending to head in that one.

**Comment by annevk** [comment]
I think going with either the IDL version or what is in HTML today is probably fine for a MVP. We can revisit once cleanup has happened.

**Comment by igrigorik** [comment]
@annevk @bzbarsky updated. not 100% on it, but I think this should be pretty close: https://github.com/w3c/performance-timeline/pull/47 - wdyt?

**Comment by annevk** [comment]
Looks okay. Probably also want to ask feedback on public-script-coord@w3.org for the design of the API.

**Comment by igrigorik** [comment]
@annevk thanks, I'll land this then and we can iterate from there.
