### ISSUE TITLE
Clarify when observe method is called more than once

### ISSUE THREAD

**Issue by hiikezoe** [w3c/performance-timeline#45]
https://w3c.github.io/performance-timeline/#widl-PerformanceObserver-observe-void-PerformanceObserverInit-options

>  If the performance observer is already registered with a Performance Timeline, update the performance observer options with options.

The 'update' is little bit confusable to me. It means replacing with the new options or merging with the new one.
I think it means 'replacing' and I've been implementing such way though.

**Comment by mpb** [comment]
I implemented as 'replacing' too.

**Comment by igrigorik** [comment]
Should we update the spec language? s/update/replace?

**Comment by hiikezoe** [comment]
@igrigorik yes,  |replace| is easy to understand to me.
