### ISSUE TITLE
Mismatches between the shortNames in the w3c.json and the WebPerf repositories

### ISSUE THREAD

**Issue by siusin** [w3c/performance-timeline#51]
@plehegar 

Most of the shortNames in the w3c.json don't match with the repositories, say performance-timeline, hr-time and performance-timeline. 

Is it for any special reason or should I fix it?

**Comment by plehegar** [comment]
No special reason but I don't think we should fix them. Goal is to have those shortnames pointing to latest. See http://www.w3.org/TR/hr-time/ for example.

**Comment by plehegar** [comment]
actually, I was wrong
 https://github.com/w3c/performance-timeline/commit/5152d4054e242f1877e024652a33bec8fa03b89c
