### ISSUE TITLE
Link to performance observer interface is incorrect

### ISSUE THREAD

**Issue by JonasNo** [w3c/performance-timeline#54]
Link: "subscribe to notifications of new performance metrics"
Wrong : https://w3c.github.io/performance-timeline/#the-performance-observer-interface
Correct: https://w3c.github.io/performance-timeline/#the-performanceobserver-interface

**Comment by igrigorik** [comment]
@JonasNo which section is this in? I can't find it.

**Comment by plehegar** [comment]
I looked into all of our webperf specs and didn't find a single occurrence of the fragment or the sentence. @JonasNo , feel free to reopen this bug if you can identify where this appears.

**Comment by JonasNo** [comment]
At the time it was wrong but now it works. This is weird.
Before I checked using devtool in Chrome. I'm mainly a Chrome user. I apologize if this have been fixed already.
(I don't even know how to reopen a bug at github.)
