### ISSUE TITLE
Ability to observers past set of performance entries

### ISSUE THREAD

**Issue by plehegar** [w3c/performance-timeline#56]
This is following:
  https://www.w3.org/2015/10/25-webperf-minutes.html#pt
 [pointer to June 2016 June 21 minutes]

Performance Observer:
  Extend filter options to support filter by name and type
  Option to receive buffered entries as first invocation callback
    Q: should we clear at some point?

**Comment by plehegar** [comment]
clarification: we'll do "Option to receive buffered entries as first invocation callback" first and then see.

**Comment by igrigorik** [comment]
@plehegar @toddreifsteck tentatively assigning this to Level 3? Or, do we think this should be a blocker for L2?

**Comment by igrigorik** [comment]
After re-reading our past discussions at F2F/TPAC... How about the following: 

As part of the "queue the performance entry" algorithm, which is called whenever a record needs to be delivered to observers, we can automatically append **all** such entries to the "performance entry buffer" while the page is loading - i.e. buffer all entries until onload event has finished executing.

This provides the following properties:

- Scripts have a well defined point by which they need to register their observers, if they want to receive entries beyond the initial page load.
- Scripts can obtain all entries queued before their observer is registered: query the buffer once (via `performance.getEntries()`), register observer to avoid polling from this point forward.
- The UA is only required to buffer up until the end of onload event.

@toddreifsteck @yoavweiss @rniwa WDYT?

**Comment by nicjansma** [comment]
Seems like a usable approach for third-party analytics.

**Comment by rniwa** [comment]
`load` event may take a while to load in some pages.  Also, if we're buffering entries, why don't we just deliver those buffered entries to the observer instead of having them look through the timeline?  We can even make it an optional behavior.

**Comment by yoavweiss** [comment]
I think this is a good approach, that'd enable analytics scripts to register in a non-blocking manner.

> load event may take a while to load in some pages.

True. We may want to also limit buffering on top of waiting for onload. (even if, as discussed in https://github.com/w3c/resource-timing/issues/89, the 150 limit we have today is pretty low for typical Web sites)

**Comment by igrigorik** [comment]
We could add a global cap on the number of entries we're willing to buffer before onload fires.. I don't have a strong opinion on this one. What would the limit be?

> if we're buffering entries, why don't we just deliver those buffered entries to the observer instead of having them look through the timeline? We can even make it an optional behavior.

As optional behavior, I think it could work. We could expose a new attribute on the options dictionary ~ `observer.observe({entryTypes: ['resource'], buffered: true})`, or some such. However, given that we already have observer code in the wild, I think it would have be off by default.

**Comment by rniwa** [comment]
Right. Because Safari hasn’t shipped the array-based performance timeline API, it’s preferable if you can do everything with `PerformanceObserver`.  That way, we might be able to sway users to adopt `PerformanceObserver` instead of the performance timeline API.

**Comment by igrigorik** [comment]
@rniwa yep, I'm a fan of that plan.

**Comment by igrigorik** [comment]
Resolved via https://github.com/w3c/performance-timeline/pull/76.
