### ISSUE TITLE
performance.getEntries() can't get failed requests.

### ISSUE THREAD

**Issue by Handsome2734** [w3c/performance-timeline#59]
For example, I added '0.0.0.0 avatars2.githubusercontent.com' into /etc/hosts, then visited github.com.
After page fully loaded, I run `performance.getEntriesByType('resource').filter(function(entry){return /avatars2\.githubusercontent\.com/.test(entry.name)});` in the console, I got nothing.
However in production env, sometimes it's important to know how many requests are timeout or aborted by the browser.
Hope there will be an api or some way to get that.

**Comment by igrigorik** [comment]
Please see https://github.com/w3c/resource-timing/issues/12.
