### ISSUE TITLE
Expose performance interface to worker

### ISSUE THREAD

**Issue by igrigorik** [w3c/performance-timeline#6]
ServiceWorker needs access to Performance interface. To enable this, I think we need to do a bit of spec shuffling and cleanup:

- Move definition of Performance interface from NavTiming ([sec 4.2](http://w3c.github.io/navigation-timing/#sec-performance-interface)) into Performance Timeline spec, and update Nav Timing language to "participate" in the timeline.
- In Perf Timeline expose Performance interface to [Window,Worker].
- Cleanup Nav/Resource/User Timing and remove references to 'window.performance'. 

@plehegar any objections?

**Comment by plehegar** [comment]
+1

**Comment by igrigorik** [comment]
- https://github.com/w3c/performance-timeline/pull/7
- https://github.com/w3c/navigation-timing/pull/10
- https://github.com/w3c/resource-timing/pull/10

@plehegar I think the above three pulls is all we need to close this out. I did a pass over User Timing as well, and it looks OK to me as is -- it doesn't make any specific references to Window, etc.

**Comment by toddreifsteck** [comment]
@plehegar should still review but... I just checked things out and it all looks good to me.

**Comment by natduca** [comment]
@KenjiBaheux fyi
