### ISSUE TITLE
Transition Level 2 to CR

### ISSUE THREAD

**Issue by igrigorik** [w3c/performance-timeline#62]
- [x] **Known / outstanding spec issues**
  - [x] document [updates from L1](https://www.w3.org/2016/06/WebPerfWGroadmap.html)
  - [x] add acknowledgement section
  - [x] resolve https://github.com/w3c/resource-timing/issues/55#issuecomment-221900695
- [x] **Privacy and security**
  - http://w3c.github.io/performance-timeline/#privacy-security
- [x] **Web platform [tests](https://github.com/w3c/web-platform-tests/tree/master/performance-timeline)**
  - https://github.com/w3c/web-platform-tests/pulls?q=is%3Apr+performance-timeline+is%3Aclosed+label%3Aperformance-timeline
- [x] **Implementations**
  - Chrome: [M52+](https://www.chromestatus.com/feature/5945504202489856)
  - Firefox: [M43](https://bugzilla.mozilla.org/show_bug.cgi?id=1165796)
  - Edge: WIP, ["Roadmap Priority: Medium"](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/performanceobserver/)
  - Safari: no public signals

**Comment by igrigorik** [comment]
- changes from L1: https://github.com/w3c/performance-timeline/commit/e67afe5f00645521a810c586236848b39b7fcf76
- ack's section: https://github.com/w3c/performance-timeline/commit/8efc38077f880b99ff233c41b70de12cd055789a
- privacy/security section: https://github.com/w3c/performance-timeline/commit/08ad1cd69286306347b755e0df0e6d00c57ef4a3

@toddreifsteck @plehegar ptal at the above.

**Comment by plehegar** [comment]
👍

**Comment by plehegar** [comment]
should we request wide review for this spec to make sure we're covered?

**Comment by igrigorik** [comment]
I didn't bring it up on the call today because I'd like to resolve https://github.com/w3c/resource-timing/issues/55#issuecomment-221900695 before we push for CR... However, I guess request for wide review doesn't need to block on that?

**Comment by plehegar** [comment]
I don't think we need to block: we could a pointer to the issue from the status to bring attention if needed. If you're ok, I'll just do the status and trigger the wide review.

**Comment by igrigorik** [comment]
Sounds good to me.

**Comment by plehegar** [comment]
Done. https://lists.w3.org/Archives/Public/public-review-announce/2016Oct/0015.html

**Comment by toddreifsteck** [comment]
This list is looking good to me so far!

**Comment by igrigorik** [comment]
Re, https://github.com/w3c/resource-timing/issues/55#issuecomment-221900695: I believe that issue is a no-op for perf-timeline and hence this is ready to go to CR.

**Comment by plehegar** [comment]
@igrigorik any chance you can look at the privacy/security section to see if it's up-to-date?

**Comment by igrigorik** [comment]
@plehegar I believe it is. As it stands, perf-timeline provides plumbing for receiving and retrieving metrics from it; on it's own it's a no-op in terms of privacy or security implications.. it only becomes relevant based on what data is pushed into it by other specs and mechanisms.

**Comment by toddreifsteck** [comment]
Doesn't Performance Timeline have some lifetime guarantees built into it to ensure it is flushed across navigates and also each subdocument has its own performance timeline. These are HTML5 requirements for any member of window but.. perhaps it is worth calling those out?

**Comment by igrigorik** [comment]
> Doesn't Performance Timeline have some lifetime guarantees built into it to ensure it is flushed across navigates and also each subdocument has its own performance timeline.

Yes, implicitly via...

> Each ECMAScript global environment has:
> - a performance entry buffer to store PerformanceEntry objects.
> ...

I guess if we want to be super explicit about it we could say...

> This specification extends the Performance interface defined by [HR-TIME-2] and provides methods to queue and retrieve entries from the performance timeline of the associated ECMAScript global environment. Please refer to [HR-TIME-2] for privacy and security considerations of exposing high-resoluting timing information.

To be honest, I don't think we want to get into discussion on how/where these globals are cleared, unloaded, etc, that should fall out from the HTML spec.

WDYT?

**Comment by toddreifsteck** [comment]
I don't disagree, but wanted us to be explicit that we were choosing not to document that. It is the only privacy item I could think of so I figured it was best to be clear that we believe it is already covered by HTML5 and should not be repeated.

**Comment by igrigorik** [comment]
Approved to publish L2 CR on today's call. 

@plehegar @siusin can you help us with the transition request and close this once that's on the way?

**Comment by plehegar** [comment]
@igrigorik I'll take care of this one today.

**Comment by plehegar** [comment]
Done: https://www.w3.org/TR/2016/CR-performance-timeline-2-20161208/
Sorry that it took so long :(
Next step will be PR in January

**Comment by igrigorik** [comment]
Thanks Philippe. Updated our dashboard, closing this..
