### ISSUE TITLE
Clarify how PerformanceObserver invokes the callback - arguments and `this` value

### ISSUE THREAD

**Issue by JosephPecoraro** [w3c/performance-timeline#65]
The [spec text](https://w3c.github.io/performance-timeline/#performance-timeline) for invoking the PerformanceObserver callback appears incorrect.

It currently says:

> If `entries` is non-empty, call `po`’s callback with `entries` as first argument and callback this value. If this throws an exception, report the exception.

I suspect it should be saying:

> If `entries` is non-empty, call `po`’s callback with `entries` as first argument and `po` as the second argument and callback this value. If this throws an exception, report the exception.

This would match behavior of [MutationObservers](https://dom.spec.whatwg.org/#notify-mutation-observers) and [IntersectionObservers](https://wicg.github.io/IntersectionObserver/#notify-intersection-observers-algo) as well as existing PerformanceObserver implementations in Chrome and Firefox.

A simple test would be:

```js
let observer = new PerformanceObserver(function(entries, po) {
    assert(entries instanceof PerformanceObserverEntryList);
    assert(po === observer);
    assert(this === observer);
});
observer.observe({entryTypes: ["mark"]);
performance.mark("test");
```

**Comment by toddreifsteck** [comment]
LGTM
