### ISSUE TITLE
Clarify disconnecting a PerformanceObserver that has observed entries

### ISSUE THREAD

**Issue by JosephPecoraro** [w3c/performance-timeline#66]
My reading of the spec says that if a PerformanceObserver is disconnected, its callback would not fire with entries. However [web-platform-tests/performance-timeline/po-disconnect.html](http://w3c-test.org/performance-timeline/po-disconnect.html) tests otherwise.

In this simple test:

```js
var observer = new PerformanceObserver(console.log);
observer.observe({entryTypes: ["mark"]});
performance.mark("mark1");
observer.disconnect();
performance.mark("mark2");
console.log("DONE");
````

My reading of the spec is:

1. observer.observe => Registers `observer`.
2. performance.mark("mark1") => Triggers _queue a PerformanceEntry_, which appends entry to observer's buffer and queues a task to *later* dispatch it.
3. observer.disconnect => Clears this observer's buffer and unregisters it.
4. Later the task runs => this observer's buffer is empty, so the callback is not invoked.

---

Implementations differ, with one matching the spec (Firefox) and one matching the tests (Chrome).

* Chrome (v58)
  Logs in callback.
  Logs DONE.

* Firefox (v54)
  Logs DONE.

**Comment by JosephPecoraro** [comment]
I feel the spec's behavior as written makes the most sense. Even though the Observer has observed an entry, the page has called `disconnect`, so it should expect NO callbacks, even if the observer had entries in its buffer.

Further, Chrome's behavior of dispatching the callback not in a task (evident by the log before DONE) is quite unusual. The expectation is that these callbacks may happen at idle times, not be forced by a call to `disconnect`.

**Comment by spanicker** [comment]
This was discussed a while ago in this bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=607324
The agreement we came to with Spec editors was that the test is correct, and when disconnect is called, the set of pending entries should be delivered / flushed as part of the disconnect flow.
So unless something has changed since then, perhaps the spec should be clarified.

@igrigorik

**Comment by JosephPecoraro** [comment]
If that is the case the Spec should make it clear when the Performance Observer's callback gets invoked from `disconnect()`. In Chrome it happens synchronously in the `disconnect()`, must like a `dispatchEvent()` synchronously invokes event handlers. This is atypical of when the callbacks normally get invoked (asynchronously when idle). Web Developers will want to know that their PerformanceObserver callbacks may be called synchronously.

**Comment by igrigorik** [comment]
/cc @overholt for comments from Moz side.

It does like we should clarify this behavior in the spec. The intent, as per the chromium bug above, was to flush and deliver all the entries that were queued prior to disconnect() call.

**Comment by JosephPecoraro** [comment]
This behavior of `disconnect()` would also differ from MutationObservers:

```html
<div id="my-div"></div>
<script>
let target = document.getElementById("my-div");
let observer = new MutationObserver(() => { console.log("Fired"); });
observer.observe(target, {childList: true});
target.appendChild(document.createElement("span"));
observer.disconnect();
</script>
```

WebKit, Chrome, and Firefox all agree to not dispatch the MutationObserver callback here. Remove the disconnect line and it does trigger.

**Comment by overholt** [comment]
@hiikezoe did the implementation in Gecko (https://bugzilla.mozilla.org/show_bug.cgi?id=1165796) and @bakulf did reviews. Maybe they have opinions?

**Comment by hiikezoe** [comment]
When I implemented PerformanceObserver,   I thought queued entries are discarded.  Actually I don't remember exactly but I wrote such test case [1].  Now I re-read the spec again,  this behavior matches to the spec.    So if the queued entries is flushed when disconnect() we might want to clarify the spec.

A reason I can think of we should discard those entries is that web developers might want to do something as a post process when disconnect().  For example:
var somethingForPO;

// initialize somethingForPO.

var observer = new PerformanceObserver(list => {
  // use somethingForPO.  
});
...
observer.disconnect();
// drop the somethingForPO or something.

[1] https://hg.mozilla.org/mozilla-central/file/e677ba018b22/dom/performance/tests/test_performance_observer.js#l165

**Comment by toddreifsteck** [comment]
Today:
* Chrome flushes on disconnect

Options:
* Align with other Observers: Chrome fixes bug to match spec, we add takeRecords to the spec
* Different than other Observers: Update spec to flush on disconnect (Seems bad.. as it doesn't allow dev to walk away from the queue)

**Comment by JosephPecoraro** [comment]
The significant use case here was if some script on the page wants to process any buffered when the page is going away (unload / pagehide), they need to have some synchronous way to get the records. Other Observers solve this with takeRecords.

**Comment by igrigorik** [comment]
We should align with takeRecords. The AI's here are: 

1. Revert Chrome's flush behavior introduced in http://crbug.com/607324
1. Remove [po-disconnect WPT test](https://github.com/w3c/web-platform-tests/blob/master/performance-timeline/po-disconnect.html#L31)
1. Introduce takeRecords... as part of Level 2?
   - @toddreifsteck @JosephPecoraro @hiikezoe @spanicker thoughts as implementers? :)

**Comment by igrigorik** [comment]
*bump*

**Comment by spanicker** [comment]
SGTM
Re: #1 feel free to file and assign crbug to me

**Comment by toddreifsteck** [comment]
LGTM

@hiikezoe @JosephPecoraro ?

**Comment by hiikezoe** [comment]
Sounds really nice. Thanks!

**Comment by igrigorik** [comment]
@spanicker I reopened http://crbug.com/607324, and I'll assume that we'll upstream the updated test as part of that. 

@toddreifsteck @hiikezoe @JosephPecoraro @spanicker should we put takeRecords under L2, or punt to L3? Personally, I'm leaning towards the latter.

**Comment by JosephPecoraro** [comment]
I have no preference for when it gets specced. Anything we do here should be trivial to implement in WebKit.

Having had some time to think about this its a bit disappointing that a takeRecords approach means entries are accessed outside the normal callback. I suspect most code would just want to invoke the original observer's callback anyways to avoid duplicating code that deals with entries. This results in clunky code that needs to "save a reference to the callback" in order to reuse it in rare takeRecords case:

```js
let observer = new PerformanceObserver(function observerCallback(entries) {
    // process entries
});
// ...
window.addEventListener("pagehide", (event) => {
    observerCallback(observer.takeRecords());
});
```

Without the takeRecords precedent, I think just having a way to synchronously flush and invoke the observer callback with any entries would have been the most natural API. For example:

```js
let observer = new PerformanceObserver((entries) => {
    // process entries
});
// ...
window.addEventListener("pagehide", (event) => {
    observer.flush();
});
```

**Comment by igrigorik** [comment]
@JosephPecoraro agreed, that would be a nicer pattern. However, I think that ship has sailed.. we should stay consistent with other *Observer patterns. 

Opened new issue to track `takeRecords()` and marked it as an L3 target. Closing this thread, let's continue the discussion in https://github.com/w3c/performance-timeline/issues/74.

**Comment by birtles** [comment]
@spanicker Would you mind reverting the [crbug](https://bugs.chromium.org/p/chromium/issues/detail?id=607324) as you mentioned in https://github.com/w3c/performance-timeline/issues/66#issuecomment-284609516. We'd like to [ship this API in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1271487) but are reluctant to do so while there is an incompatibility with Chrome.

**Comment by yoavweiss** [comment]
Seems like the Chrome behavior was [reverted](https://bugs.chromium.org/p/chromium/issues/detail?id=607324#c8).
