### ISSUE TITLE
Clarify sort order for entries with equivalent startTime

### ISSUE THREAD

**Issue by JosephPecoraro** [w3c/performance-timeline#67]
The spec says that entries in PerformanceObserverEntryList should be [sorted by start time](https://w3c.github.io/performance-timeline/#filter-performance-entry-buffer-by-name-and-type):

> Given optional name and type string values this algorithm returns a PerformanceEntryList object that contains a list of PerformanceEntry objects, sorted in chronological order with respect to startTime.

However, many entries may contain equivalent `startTime` and implementations may differ on how these are sorted.

In this test:

```js
function wait() {
    let now = performance.now();
    while (now === performance.now())
        continue;
}

let observer = new PerformanceObserver((list) => {
    for (let mark of list.getEntries())
        console.log(mark.name + " - " + mark.startTime);
});

observer.observe({entryTypes: ["mark", "measure"]});
performance.mark("mark1");
performance.measure("measure1");
wait(); // Ensure mark1 !== mark2 startTime by making sure performance.now advances.
performance.mark("mark2");
performance.measure("measure2");
performance.measure("measure-matching-mark2-1", "mark2");
wait(); // Ensure mark2 !== mark3 startTime by making sure performance.now advances.
performance.mark("mark3");
performance.measure("measure3");
performance.measure("measure-matching-mark2-2", "mark2");
```

With times: `0 < t1 < t2`:

* measure1, measure2, and measure3 will have a startTime of `0`
* mark1 will have a startTime of `t1`
* mark2, measure-matching-mark2-1, measure-matching-mark2-2 will match `t1`
* mark3 will have a startTime of `t2`

---

Implementations sort these differently:

* Chrome (v58)
measure1 - 0
measure3 - 0
measure2 - 0
mark1 - 110.115
measure-matching-mark2-1 - 110.14
mark2 - 110.14
measure-matching-mark2-2 - 110.14
mark3 - 110.155

* Firefox (v54)
No sort whatsoever.

Take just the top 3 in Chrome. It feels weird to have `measure2` sorted after `measure3` even though they have the same `startTime`.

**Comment by JosephPecoraro** [comment]
If the spec wants to clarify this, it can mention that PerformanceEntry creation time should be used when startTime is equivalent. Otherwise the spec can be have a note that implementations may differ on the sort of equivalent startTime entries.

Either way, I can add a web-platform-test for sort.

**Comment by toddreifsteck** [comment]
Conclusion from the 2/8 W3C call: Keep the startTime ordering. Sites may depend on this. Add a note that entries with the same startTime have unspecified ordering.
