### ISSUE TITLE
Existing Test gap: Verify that toJSON output is created properly

### ISSUE THREAD

**Issue by toddreifsteck** [w3c/performance-timeline#83]
The WebIDL test verifies the existence of the method, but we've seen that sometimes properties are not serialized properly historically. We need a test for this.

**Comment by plehegar** [comment]
Addressed in https://github.com/w3c/web-platform-tests/pull/7489

**Comment by igrigorik** [comment]
@plehegar did you have another link in mind? I don't think #7489 resolves this? Or.. does it? :)

**Comment by toddreifsteck** [comment]
@plehegar @igrigorik My read of the submission is that Philippe knows that all objects instantiated and fed into the IDL array are verified against the WebIDL that is part of the test. Philippe, is that accurate?

**Comment by plehegar** [comment]
@toddreifsteck indeed. All instantiated objects are checked against their WebIDL definition, as long as those are part of the definitions to check (ie in the add_idls part, not in add_untested_idls). Run http://w3c-test.org/resource-timing/idlharness.html on Firefox and Chrome to see it in operation. The toJSON test will now ignore any unknown entries but ensure that the required entries are there.

**Comment by igrigorik** [comment]
👍
