### ISSUE TITLE
Step 1 of "observe" is not clear

### ISSUE THREAD

**Issue by bzbarsky** [w3c/performance-timeline#89]
https://w3c.github.io/performance-timeline/#dom-performanceobserver-observe() says:

> Filter unsupported names within the entryTypes sequence, and replace the entryTypes sequence with the new filtered sequence. 

Does that mean to replace it with the sequence containing only the unsupported names, the sequence _not_ containingthe unsupported names, or something else?  The verb "filter" as used here does not make it clear what sort of filtering is going on.

It would probably be clearer to just say "remove all unsupported names from the entryTypes sequence".

**Comment by igrigorik** [comment]
Yep, good call, I'll use your suggested text.
